language: python

cache: pip

install: pip install --upgrade tox setuptools virtualenv
script: python -m tox

matrix:
  include:
    - python: "3.4" # DEPRECATED
      env: TOXENV=flake8,py34-codecov
    - python: "3.5"
      env: TOXENV=mypy,flake8,py35-codecov
    - python: "3.6"
      env: TOXENV=mypy,flake8,py36-codecov
    - python: "3.7"
      env: TOXENV=mypy,flake8,py37-codecov
