language: python

cache: pip

install: pip install --upgrade tox setuptools virtualenv
script: python -m tox

matrix:
  include:
    - python: "3.4"
      env: TOXENV=linter,codestyle,testing,coverage,codecov
    - python: "3.5"
      env: TOXENV=linter,codestyle,testing,coverage,codecov
    - python: "3.6"
      env: TOXENV=linter,codestyle,testing,coverage,codecov
    - python: "3.7"
      env: TOXENV=linter,codestyle,testing,coverage,codecov
